# Changes here will be overwritten by Copier
_commit: v0.2.5
_src_path: gh:ninanor/python-template
author_name: ninanor
debug: false
default_branch_name: main
docker: false
email: ninanor@nina.no
notebook: false
project_name: GPS Logger Parser
project_slug: gps_logger_parser
repo_name: gps_logger_parser
repo_org: ninanor
template_type: python
type_annotations: true
