name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@e92bafb6253dcd438e0484186d7669ea7a8ca1cc # v6.4.3

      - name: Install dependencies
        run: uv sync --frozen

      - name: Run tests
        run: uv run coverage run -m pytest

      - name: Generate coverage report
        run: uv run coverage xml

      - name: Code Coverage Summary
        uses: insightsengineering/coverage-action@f3f8cdb7a8863fb60236982ac44b9ae63c768cd4
        with:
          path: coverage.xml
          threshold: 50
          fail: true
          publish: true
          diff: true
          uncovered-statements-increase-failure: false
          new-uncovered-statements-failure: false
          coverage-rate-reduction-failure: true
          token: ${{ github.token }}
